### ISSUE TITLE
Impossible to update Scryfall

### ISSUE THREAD

**Issue by ciufflegend** [EskoSalaka/mtgtools#15]
Hi,
I cannot update scryfall, mtgio completly working.
Here the traceback:

`Processing responses: [695 / 831]Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/.local/lib/python3.8/site-packages/mtgtools/MtgDB.py", line 182, in scryfall_update
    process_scryfall_cards(current_sets, current_cards, verbose=verbose, workers=workers)
  File "/home/daniel/.local/lib/python3.8/site-packages/mtgtools/util/api_requests.py", line 167, in process_scryfall_cards
    ])
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/daniel/.local/lib/python3.8/site-packages/mtgtools/util/api_requests.py", line 203, in process_cards
    await asyncio.sleep(0.1)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 608, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/daniel/.local/lib/python3.8/site-packages/mtgtools/util/api_requests.py", line 35, in process_card_page_response
    else:
KeyError: 'data'
`

**Comment by shcoops** [comment]
Having a similar issue. Stuck processing responses between 40/831 and 700/831. Getting ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host.

**Comment by AndrewWigman** [comment]
Also having this issue, don't suppose anyone has figured it out in the past 6 months?

**Comment by shcoops** [comment]
@AndrewWigman I had the issue when I was pulling from the Pip directory. If you haven't already, try installing directly from GitHub and see if that resolves it, it worked for me.

**Comment by EskoSalaka** [comment]
Sorry guys, past year has been quite busy for me and I have not been able to update this project much at all! I know that some changes indeed are not yet in PIP. 

It could also be that Scryfall API has changed a bit and it could be there are stricter limits on how much one can use the API. I know that they are at least offering a ZIP of all the cards, which would be a better way of updating the database. 

Ill try to take a look soon...

**Comment by shcoops** [comment]
It worked perfectly when I imported from Git! Thanks

**Comment by EskoSalaka** [comment]
The fixes along with a new update method that uses the bulk data from Scryfall are now also in PYPI!
